# .github/workflows/deploy.yml 파일

name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    env:
      CI: false # 경고를 오류로 취급하지 않음

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # ... (Node.js 설치 및 의존성 설치)

      - name: Build Project
        run: npm run build 
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build